### ISSUE TITLE
Couple of warnings (might not affect anything)

### ISSUE THREAD

**Issue by reedM2** [alainbryden/bitburner-scripts#17] opened 2021-12-30 04:27 UTC
Hi,

just a couple of warnings that keep popping up, I just wanted to let you know

1.)
daemon.js: WARNING: Caught an error in the targeting loop: TypeError: Cannot read properties of null (reading 'ramAvailable')

2.)
Warning, hack stole 0 money. Might be a misfire. ["omega-net",1640838358728,1640838423852,65124,"Batch 12-hack",0,0,0]

**Comment by alainbryden** [comment] 2021-12-30 14:11
I suspect the first issue can only occur if you are deleting servers manually while the daemon is actively running. If that's the case, then there's 100s of places where such issues can occur and I've intentionally dealt with them by wrapping the entire main loop in a try/catch and simply updating the list of available servers on the next iteration.

Let me know if that's what you did to cause it, and I'll close this as working as expected.

Second is definitely intended behaviour. If your cycle timing is configured too tight, or your computer is lagging or putting the tab to sleep, you will get "misfires" and your hack/grow/weaken calls will fail to have the desired effect. This is an expected part of cycle timing, and these warnings are to help you identify systematic issues and adjust your timing to correct them.

**Closed** 2021-12-30 14:12 UTC
Labels: wontfix
